### ISSUE TITLE
Entries do not update automatically

### ISSUE THREAD

**Issue by GigiPompieru** [rowysock/home-assistant-HomeWhiz#126]
The sensors in Home Assistant do not update automatically, even if the cloud info gets updated from the device.
Reloading the integration fetches the new data.

![image](https://user-images.githubusercontent.com/28728401/233580098-ec9d1247-965d-45ba-9cbd-ba2d1d32fe7d.png)

**Comment by TechHummel** [comment]
Which version are you using? Can you try using the version from the main branch? If this doesn't help, we will need logs.

**Comment by macicek86** [comment]
if you install this from hacs Is required select in version menu version "main" not V4 . 
This works!!

**Comment by GigiPompieru** [comment]
> 

can I change this? if so, how, or do I need to reinstall it.

**Comment by macicek86** [comment]
Do in repository menu of Hacs. Try download again and change from version 4.0 to "main"

**Comment by GigiPompieru** [comment]
> 

did, thanks, it's funny that now it wants to update...

![Screenshot_20230422_162259_Home Assistant](https://user-images.githubusercontent.com/28728401/233787721-78e8beb7-cf04-4b9c-8317-59671b4776e5.png)

**Comment by macicek86** [comment]
It's true . Ignore it. That's work!!

**Comment by TechHummel** [comment]
I understood that it's working now? I'll close the issue then 😄

**Comment by mstipanov** [comment]
It is still not resolved for me. I have BEKO AC and for example, if I switch hvac mode from "cool" to "fan", the action is executed on the AC, but on HA is still says "cool". This changes only when I open the HomeWhiz app on my phone.

I'm using the master version.

There is also a "bug": "off" state is not interpreted as havc_mode="off", because The app reports "cool" state event when it is off :(
