### ISSUE TITLE
New SubStates IDLE and DRYING

### ISSUE THREAD

**Issue by TechHummel** [rowysock/home-assistant-HomeWhiz#28]
Followup issue from #16:
> and add 2 line to homewhiz.py: IDLE = 0 and DRYING = 21.
>
> P.S. digging trough com.homewhiz.global_2022-11-16.apk\resources\assets found these mapping files.

**Comment by StarvingDeveloper** [comment]
I wrote very long replay with logs and screenshots but it gone with electricity jump and dont have another hour to rewrite it, so just short answer:

substate 21 looks right - dosent matter I start cotton or synthetic drying program it is always 21.

I think substate 0 dont exist That come from 3 instead of 2 lines sometimes I am getting - array get longer and [parser](https://github.com/rowysock/home-assistant-HomeWhiz/blob/09f988b98d38367d37a324ecc0593c49bcf39327/custom_components/homewhiz/homewhiz.py#L91) dosent work as suppose. 
And as I [stated yesterday](https://github.com/rowysock/home-assistant-HomeWhiz/pull/22?notification_referrer_id=NT_kwDOAT88ULM0OTA0NTI1OTMzOjIwOTIxNDI0#issuecomment-1326028661) when I am used steam I also was getting substate 0, but was not logging whole messages, just substate, so cant be sure, but I think I was getting 3 lines while steam program was going on and that why sub_state was showing 0.
Next time I will use steam program I can check this my theory. Meanwhile you could improve merge and parse code, so it wont goes wrong when message got 3 lines. 
Hooray to @TechHummel who got caught to this project :)

**Comment by rowysock** [comment]
@StarvingDeveloper can you provide the product number you enter when adding a new device in the original app?

**Comment by rowysock** [comment]
@StarvingDeveloper in the topic of line count: the original app perform the accumulation in `com.arcelikiot.communication.ble.service.protocol.BleControlService#handleWfaResponse`
It expects only 2 messages first of length 33 and second of length 7, after that it logs "Unexpected wfa index"

**Comment by StarvingDeveloper** [comment]
> @StarvingDeveloper can you provide the product number you enter when adding a new device in the original app?

where I can check this number? I add machine few years ago and wasnt using it at all till HA.



> @StarvingDeveloper in the topic of line count: the original app perform the accumulation in `com.arcelikiot.communication.ble.service.protocol.BleControlService#handleWfaResponse` It expects only 2 messages first of length 33 and second of length 7, after that it logs "Unexpected wfa index"

ok, but as you could [see here](https://github.com/rowysock/home-assistant-HomeWhiz/pull/22?notification_referrer_id=NT_kwDOAT88ULM0OTA0NTI1OTMzOjIwOTIxNDI0#issuecomment-1326435796) my strings really different  T_T

**Comment by StarvingDeveloper** [comment]
Btw can it be reason why even 0.6 version still crash exactly after 45 minutes after washing started. It update time and status first 45 minutes, then this error show up in logs till I turn off machine:
```
2022-11-25 15:08:56.056 WARNING (MainThread) [custom_components.homewhiz] message 1
<skipped some entries as they not important to save space>
2022-11-25 15:52:56.894 WARNING (MainThread) [custom_components.homewhiz] message 1
2022-11-25 15:53:10.358 WARNING (MainThread) [custom_components.homewhiz] [org.bluez.Error.Failed] le-connection-abort-by-local
2022-11-25 15:53:48.591 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/homewhiz/__init__.py", line 85, in reconnect
    await self.client.stop_notify("0000ac02-0000-1000-8000-00805f9b34fb")
  File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 667, in stop_notify
    await self._backend.stop_notify(char_specifier)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 917, in stop_notify
    assert_reply(reply)
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.Failed] No notify session started
```
Btw this behavior was from the start and I was keep moving raspberry closer and closer to the washer, till today I put him next to machine and after 45 minutes it still crashed. Same as it was from 5 meters away, so it's not about distance. Problem somewhere in the code, because as you can see from the logs it crash every time exactly after 45 minutes. Must be some buffer overflow or something. I know more about animals python as about programing language, so just guessing.

**Comment by rowysock** [comment]
@StarvingDeveloper the product number should be 10 digits long, written above barcode probably behind washing machine door

**Comment by rowysock** [comment]
I've also checked the communication with my washing machine and I also get the 3 messages like 
```
2022-11-26 01:00:32.718 DEBUG (MainThread) [custom_components.homewhiz] message bytearray(b'\x02\x01\x00\x00')
2022-11-26 01:00:32.718 DEBUG (MainThread) [custom_components.homewhiz] message bytearray(b'\x02\x04<\x00\x00\x009\x00/JE\xa1\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\n\x01(\x0c\x00\x00\x00\x00\x80\x02\x11\x02\x11\x00\x00\x00\x00\x00\x00\x00\x00\x00')
2022-11-26 01:00:32.719 DEBUG (MainThread) [custom_components.homewhiz] message bytearray(b'\x02\x04\x17\x00\x01\x00\x14\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x01\x07\x00\x00\x00\x00\x00')
```

The firts one is just not interesting and is being ignored. 

However the fail after exactly 45 minutes is very strange. I suspect that has something to do with the previous line: `le-connection-abort-by-local` caused by the bluez which is a system service
I thnk ignoring error in `stop_notify` operation should be safe

**Comment by StarvingDeveloper** [comment]
> @StarvingDeveloper the product number should be 10 digits long, written above barcode probably behind washing machine door

![e08910f4-3126-4260-ae73-bf0956fcd225](https://user-images.githubusercontent.com/20921424/204075952-83f8df88-c610-4c0e-a64b-cffbf42e4d48.jpg)

> The firts one is just not interesting and is being ignored.

In official app maybe, but your integration when 3 lines  message give substate code 0. And as I stated before some washing programs sends 3 lines message, so substate index become not 50, but slightly higher and we see unknown (0) substate.

**Comment by rowysock** [comment]
I have an interesting discovery to share: 

There are mapping files in the original app, that describe which parts of the combined bluetooth message correspond to what information. I initially assumed that the app somehow decided on which file to use based on the model number. 
It was strange, because none of the files contained value 21 for substate, while it was observed to be present.

I've discovered that the app takes the mapping files from the API. I've successfully intercepted the app communication and discovered, that the api returns different mapping files than those stored inside the app. In the api mapping indeed there is a value 21 for substate with key WASHER_SUBSTATE_DRYING. 

I presume the files in the app are obsolete and not used in reality

That means that to correctly decode the Bluetooth communication we have to connect to an authorized HTTP API. 
We have to ask users to provide their Homwehiz username and password. Ideally, we should be able to ask users to provide their username and password via config flow, alternatively, we can choose the simple approach and tell users to set HomeWhiz username and password in the config.yml @TechHummel what do you think about that?

**Comment by TechHummel** [comment]
That is a surprising discovery you made there 🥳.

I do like the idea of dynamically downloading mappings from the API, but I am honestly not sure if it is worth implementing. When we add substate 21 to the mapping in this integration, we will likely cover all HomeWhiz washing machines already (at least no users complained about wrong mappings yet). It would be interesting for supporting other HomeWhiz devices eventually. On the other hand, missing mappings could be downloaded by us or provided by users and then added to this integration. If, at some point, this integration does no longer rely on the HomeWhiz app, we could offer users interacting with their devices without needing accounts at all. 
Basically, it depends on how much variety there is in the mappings 😄

**Comment by StarvingDeveloper** [comment]
Nice discovery!
So in these mapping files should be program names too? Like in official app

![c6cc2cbe-c9fb-4033-bdc2-b66d25a42302](https://user-images.githubusercontent.com/20921424/204222582-8faa5ed7-5e9c-4064-a4ad-185284738fcb.jpg)

I mean currently running "cotton dry" not just "running" state.

As about connect to API every time that really bad idea, because integration wont work without internet - now enough have local network. These mapping files change on very rare occasions, so better get them all and keep inside integration.

And only me have [this problem](https://github.com/rowysock/home-assistant-HomeWhiz/issues/28?notification_referrer_id=NT_kwDOAT88ULM0OTI1MzMzNzY1OjIwOTIxNDI0#issuecomment-1327800129)? And why I must restart whole HA to make integration work again?

**Comment by TechHummel** [comment]
I personally think that as long as there are no collisions between mapping files, using a mapping file with all possible states even for basic washing machines should not be an issue. Or did you also stumble across substates with the same number and different meaning? Then I would 100% agree with using the API.
Talking about the different appliances: You are right. This could also be solved by a basic "select your appliance" during setup, though.

I am a bit undecided. Using the API makes it more flexible and future-proof, but requires users to register and could result in us having to adjust code constantly as the APIs might change.
Would you still be worried about intellectual property if we only collect the substates from the original mapping files but don't use the files directly? So something similar to what is used right now?

**Comment by rowysock** [comment]
@TechHummel sorry, for the late response. I've wanted to dig through the API a little bit more. 

Asking the user to select the appliance type is a smart idea. Users should know whether they are setting up a washing machine or an oven. 

IMO creating a single mapping file with all possible states is not possible in practice, collisions are unavoidable.  

I wished that there is a way to iterate over all of the possible devices and fetch their mapping from the API, but I see no way of doing that, unfortunately. We can get a mapping only by the "digital id", which is retrieved after providing the Bluetooth device name. We have no way of telling what Bluetooth device names are out there. 

My gut feeling is that the API will not evolve over time, as the arcelik has to keep it backward compatible with older application versions. What may change are the mappings for new devices.

We have two options: 
1. Ask users to select the appliance type and select mapping based on that
  Pros:
  - Fully offline
  Cons:
   - We can use only device types that are already in the app (newer ones may be available)
   - We can use only the mapping files that are already present in the app (new versions may be available as shown by SubSatte Drying)
   - Converting all of the built-in mappings can be a lot of work
2. Ask users to provide HomeWhiz username and password
  Pros:
  - Always the up to date
  - We can write parsing code once and then use it for all of the appliances
  - Querying API is actually quite simple (I have a working proof-of-concept already working)
  - We can use the device name provided by the user in the HomeWhiz app to name the device instead of using MAC address or Bluetooth name
  - Username, password, nor any token won't be stored anywhere
  Cons:
  - HomeWhiz account is required
  - Internet connectivity is required (only during configuration, as we can store the mapping in HA)
  - Users may possibly not want to provide their username and password into the random HACS integration (?)

**Comment by rowysock** [comment]
IMO it boils down to the question: Do we want the integration to be fully-offline or future-proof?
