### ISSUE TITLE
Blomberg washing machine data refresh

### ISSUE THREAD

**Issue by JoesDegz** [rowysock/home-assistant-HomeWhiz#29]
Connected Blomberg machine but to refresh data integration has to be reloaded everytime.  Using the esp32 bluetooth proxy.

**Comment by rowysock** [comment]
Can you provide the logs?

**Comment by JoesDegz** [comment]
Last night i upgraded the integration and tomorrow it looks that it is
working fine.  This is the third wash i am doing and it is working fine.
What i found out is that when i went to create an automation so that i am
notified when the washing is ready only 5 entities are available and
unfortunately sub-state is not one of them.  Finally thanks for the
integration, people like you make the world a better place.

**Comment by TechHummel** [comment]
I can select substate when building automations. 
![image](https://user-images.githubusercontent.com/15891478/204111430-7946ccc4-4525-4800-808e-50d6c062646b.png)
This is not working for you?

**Comment by StarvingDeveloper** [comment]
@TechHummel I think Joes trying add automation via device instead of state

![Untitled1](https://user-images.githubusercontent.com/20921424/204225568-d60896bf-2149-4cba-ab0f-4df4eb0c60e0.png)

so he getting only these 5 options

![Untitled2](https://user-images.githubusercontent.com/20921424/204225651-aae6f743-439a-479a-84d4-2a6bbc7452c3.png)

so he need make automation with state and then have all these entities. But states I still must enter with hands, because I am getting only 3 useless values

![Untitled3](https://user-images.githubusercontent.com/20921424/204226144-40ef4f87-a704-43fc-be46-5acac5457a32.png)

I would like to have there substates like
WASHING = 1
SPIN = 2
WATER_INTAKE = 3
PREWASH = 4

**Comment by TechHummel** [comment]
I'll close this for now. You can try the latest version (main branch) and let us know if there is still something not working for you.
